[versions]
kotlin = "1.6.21"

[libraries]
kotlin = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }
google-ksp = { module = "com.google.devtools.ksp:symbol-processing-api", version = "1.6.21-1.0.5" }
google-truth = { module = "com.google.truth:truth", version = "1.1.3" }